theme: jekyll-theme-cayman
title: DetExploit
description: OSS Vulnerability Scanner that detects any vulnerable software on Windows
show_downloads: false
github:
  repository_url: https://github.com/detexploit/DetExploit
