theme: jekyll-theme-cayman
title: DetExploit
description: OSS vulnerability scanner that scans any vulnerable software on Windows
show_downloads: false
github:
  repository_url: https://github.com/detexploit/DetExploit
